### ISSUE TITLE
Замечания к README

### ISSUE THREAD

**Issue by kirill-kornyakov** [UNN-VMK-Software/mp2-lab1-set#5]
- [x] Исправить "Среда разработки Microsoft Visual Studio (> 2008)." на "Среда разработки Microsoft Visual Studio (2008 или старше)."
- [x] Исправить "Она может быть использована для генерации решения для среды разработки, отличной от Microsoft Visual Studio." на "Она может быть использована для генерации решения для среды разработки, отличной от Microsoft Visual Studio 2008 и 2010, предоставленных в данном проекте."
- [x] Исправить в фразе "директория с файлами решений и проектов для VS 2008 и VS2010" слово "VS2010" на "VS 2010".
- [x] Нужно ли включать в этот шаблон и соответственно описывать .travis.yml? Вроде бы мы не планировали использовать Travis в этом семестре. Кирилл, вроде бы ты не будешь об этом рассказывать на лекциях, так?
- [x] Удалить в фразе "Последовательность действий, которую необходимо выполнить описана перед началом работы с проектом" слово "описана".
- [x] В этом же пункте: перейдя по ссылке "Общие инструкции по работе с Git", я не увидел инструкции. Видимо, ссылка неверна, поскольку инструкции находится здесь же ниже по тексту? Нужно исправить ссылку.
- [x] Исправить "Текущая компилируемая версия основной функции зависит," на "Текущая компилируемая версия основной функции зависит от того,".
- [x] Исправить в фразе "После реализации каждого метода пересобирайте решение и запускайте тесты, чтобы отслежить корректность" слово "отследить" в п. 5 и п. 7.
- [x] Исправить "После того, как вы убедились, что ВСЕ тесты для класса битового поля" в п.8 на "После того, как вы убедились, что ВСЕ тесты для класса множество".
- [x] В пункте 2 "Сделать fork..." не указано, как именно его сделать (команда git и/или команда на сайте github или что-то еще).
- [x] До строки "При работе с файлами в ветке необходимо управлять изменениями." в инструкции к Git все понятно. Здесь же возникает сбой в последовательности. Упоминаются ветки, но ничего не сказано о том, как их создавать?
- [x] По проектам для MS VS (смотрел в VS 2008) у меня только одно замечание: я предлагаю вернуть файлу sample_prime_numbers.cpp исходное имя main.cpp, тем более, что оно прописано в его шапке "// main.cpp - Copyright (c) Гергель В.П. 20.08.2000"

**Comment by alvls** [comment]
Внес правки по всем замечаниям, которые я предлагал, кроме одного.
